### ISSUE TITLE
magento 2.4 problem 

### ISSUE THREAD

**Issue by Watch3ruk** [magento-research/magento2-upward-connector#38] opened 2021-09-27 17:00 UTC
Problem 1
    - Root composer.json requires magento/module-upward-connector ^1.2 -> satisfiable by magento/module-upward-connector[1.2.0].
    - magento/upward 1.1.5 requires zendframework/zend-stdlib ^2.7 || ^3.2 -> satisfiable by zendframework/zend-stdlib[2.7.0, ..., 2.7.7, 3.2.0, 3.2.1].
    - laminas/laminas-stdlib 3.6.0 conflicts with zendframework/zend-stdlib 3.2.1.
    - laminas/laminas-stdlib 3.6.0 conflicts with zendframework/zend-stdlib 3.2.0.
    - laminas/laminas-stdlib 3.6.0 conflicts with zendframework/zend-stdlib 2.7.7.
    - laminas/laminas-stdlib 3.6.0 conflicts with zendframework/zend-stdlib 2.7.6.
    - laminas/laminas-stdlib 3.6.0 conflicts with zendframework/zend-stdlib 2.7.5.
    - laminas/laminas-stdlib 3.6.0 conflicts with zendframework/zend-stdlib 2.7.4.
    - laminas/laminas-stdlib 3.6.0 conflicts with zendframework/zend-stdlib 2.7.3.
    - laminas/laminas-stdlib 3.6.0 conflicts with zendframework/zend-stdlib 2.7.2.
    - laminas/laminas-stdlib 3.6.0 conflicts with zendframework/zend-stdlib 2.7.1.
    - laminas/laminas-stdlib 3.6.0 conflicts with zendframework/zend-stdlib 2.7.0.
    - magento/product-community-edition 2.4.3 requires laminas/laminas-stdlib ^3.2.1 -> satisfiable by laminas/laminas-stdlib[3.6.0].
    - magento/module-upward-connector 1.2.0 requires magento/upward ^1.1.5 -> satisfiable by magento/upward[1.1.5].
    - magento/product-community-edition is locked to version 2.4.3 and an update of this package was not requested.

**Comment by tjwiebell** [comment] 2021-09-30 13:05
Closing as duplicate of #37 where patch and timeline was provided.

**Closed as completed by tjwiebell** 2021-09-30 13:05 UTC
