### ISSUE TITLE
magento 2.4.3 installation issue

### ISSUE THREAD

**Issue by mohdaali27** [magento-research/magento2-upward-connector#39] opened 2021-09-30 10:01 UTC
I am installing the extension using composer -  **composer require magento/module-upward-connector** but getting the below error 
![image](https://user-images.githubusercontent.com/80909837/135432390-c5832087-d79e-458d-a97a-376bea4d91d0.png)

How can we install the extension for magento 2.4.3 ?

**Comment by tjwiebell** [comment] 2021-09-30 13:04
Closing as duplicate of #37. Please see comments section for immediate patch and estimated timeline to publish fix.

**Closed as completed by tjwiebell** 2021-09-30 13:04 UTC
